server.port=8081
app_key=PSnea76T4dP1xqrq1COEEgzjleNBrjF837MZ
app_secret=+M3V+/UjlxckHNxJxQTOVmaRuxc7uyiFfiSm6mJtwRDsbLGPYSQtvBnMwIn+4fVmNg5ofcNr2+TVsYNQ2hXbaOzwbrMu9AJjTMOfbN4Rzw1+mcgDa9KxTTuyhLe0JfA14EVD7/CtsMm5+zZ9Dcbfuca+W/wRIJIoEbXHNTRfO+PSVwx4Z+0=
account_no=6408574810
webhook.slack.url=https://hooks.slack.com/services/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