rl=ws://ops.koreainvestment.com
port=21000
server.port=8081
app_key=PSnea76T4dP1xqrq1COEEgzjleNBrjF837MZ
app_secret=+M3V+/UjlxckHNxJxQTOVmaRuxc7uyiFfiSm6mJtwRDsbLGPYSQtvBnMwIn+4fVmNg5ofcNr2+TVsYNQ2hXbaOzwbrMu9AJjTMOfbN4Rzw1+mcgDa9KxTTuyhLe0JfA14EVD7/CtsMm5+zZ9Dcbfuca+W/wRIJIoEbXHNTRfO+PSVwx4Z+0=
account_no=6408574810
personal_sec_key=+M3V+/UjlxckHNxJxQTOVmaRuxc7uyiFfiSm6mJtwRDsbLGPYSQtvBnMwIn+4fVmNg5ofcNr2+TVsYNQ2hXbaOzwbrMu9AJjTMOfbN4Rzw1+mcgDa9KxTTuyhLe0JfA14EVD7/CtsMm5+zZ9Dcbfuca+W/wRIJIoEbXHNTRfO+PSVwx4Z+0=
cust_type=P
content_type=utf-8
stock_code=005930
hts_id=101334
webhook.slack.url=https://hooks.slack.com/services/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
account.balance=https://openapi.koreainvestment.com:9443/uapi/overseas-price/v1/quotations/price
nasdaq=ws://ops.koreainvestment.com:21000/tryitout/HDFSCNT0